name: swiggy CI

on:
  push:
    branches: [ "main" ]

jobs:

  testing_code:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: ls

  Docker_image_build:
    needs: testing_code
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
