name: swiggy CI

on:
  push:
    branches: [ "main" ]

jobs:

  compile:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
          
      - run: npm install
      - run: npm test
      - run: npm run build

  security-check:
    runs-on: self-hosted
    needs: compile

    steps:
      - uses: actions/checkout@v4

      - name: Trivy Installation
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.18.3_Linux-64bit.deb

      - name: Trivy FS Scan
        run: trivy fs --format table -o fs-report.json .

  Docker_image_build:
    runs-on: self-hosted
    needs: security-check

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t swiggy/image:${{ github.sha }} .
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push swiggy/image:${{ github.sha }}
      
