name: swiggy CI

on:
  push:
    branches: [ "main" ]

jobs:

  Install_dependece:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
          
      - run: npm install
      

  security-check:
    runs-on: ubuntu-latest
    needs: Install_dependece

    steps:
      - uses: actions/checkout@v4

      - name: Trivy Installation
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.18.3_Linux-64bit.deb

      - name: Trivy FS Scan
        run: trivy fs . > trivyfs.txt


  Docker_image_build:
    runs-on: self-hosted
    needs: security-check

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: sivabalan2510/app:latest
          file: ./Dockerfile

  Trivy_scanning:
        runs-on: self-hosted

        steps:
         - uses: actions/checkout@v4
         - name: scaning the image
           uses: trivy image sivabalan2510/app:latest > trivyimage.txt

      
